Dockerfiles/docker-compose.yml
setup.sh
web_data/backend/requirements.txt
web_data/backend/server/functions/breaches.py
web_data/backend/server/functions/server.py
web_data/backend/server/main.py
web_data/backend/server/routes/auth_routes.py
web_data/backend/server/routes/breaches_routes.py
web_data/backend/server/routes/server_routes.py
web_data/backend/server/server_config.yml
web_data/frontend/breaches.html
web_data/frontend/dist/customjs/dashboard.js
web_data/frontend/dist/customjs/leaklense.js
web_data/frontend/dist/customjs/leaklensedebug.js
web_data/frontend/index.html
web_data/frontend/search.html
web_data/frontend/settings-server.html
web_data/frontend/settings.html
web_data/frontend/users.html
